ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Création de l'utilisateur observateur
CREATE USER CYPI_PAU_LECTEURSEUL IDENTIFIED BY your_password;
GRANT CYPI_PAU_LECTEURSEUL TO CYPI_PAU_LECTEURSEUL;

-- Création de l'utilisateur analyste
CREATE USER CYPI_PAU_LECTURE_ECRITURE IDENTIFIED BY your_password;
GRANT CYPI_PAU_LECTURE_ECRITURE TO CYPI_PAU_LECTURE_ECRITURE;

-- Création de l'utilisateur développeur
CREATE USER CYPI_PAU_GESTIONNAIRE IDENTIFIED BY your_password;
GRANT CYPI_PAU_GESTIONNAIRE TO CYPI_PAU_GESTIONNAIRE;

-- Création de l'utilisateur administrateur
CREATE USER CYPI_PAU_ADMIN IDENTIFIED BY your_password;
GRANT CYPI_PAU_ADMIN TO CYPI_PAU_ADMIN;

COMMIT;
EXIT;
