ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Création de l'utilisateur superviseur
CREATE USER CYPI_PAU_SUPERVISEUR1 IDENTIFIED BY your_password;
GRANT CYPI_PAU_SUPERVISEUR TO CYPI_PAU_SUPERVISEUR1;

-- Création de l'utilisateur expert
CREATE USER CYPI_PAU_EXPERT1 IDENTIFIED BY your_password;
GRANT CYPI_PAU_EXPERT TO CYPI_PAU_EXPERT1;

-- Création de l'utilisateur ingénieur
CREATE USER CYPI_PAU_INGENIEUR1 IDENTIFIED BY your_password;
GRANT CYPI_PAU_INGENIEUR TO CYPI_PAU_INGENIEUR1;

-- Création de l'utilisateur responsable
CREATE USER CYPI_PAU_RESPONSABLE1 IDENTIFIED BY your_password;
GRANT CYPI_PAU_RESPONSABLE TO CYPI_PAU_RESPONSABLE1;

COMMIT;

