ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Création de l'utilisateur observateur
CREATE USER CYPI_CERGY_OBSERVATEUR1 IDENTIFIED BY your_password;
GRANT CYPI_CERGY_OBSERVATEUR TO CYPI_CERGY_OBSERVATEUR1;

-- Création de l'utilisateur analyste
CREATE USER CYPI_CERGY_ANALYST1 IDENTIFIED BY your_password;
GRANT CYPI_CERGY_ANALYST TO CYPI_CERGY_ANALYST1;

-- Création de l'utilisateur développeur
CREATE USER CYPI_CERGY_DEV1 IDENTIFIED BY your_password;
GRANT CYPI_CERGY_DEV TO CYPI_CERGY_DEV1;

-- Création de l'utilisateur administrateur
CREATE USER CYPI_CERGY_ADMIN1 IDENTIFIED BY your_password;
GRANT CYPI_CERGY_ADMIN TO CYPI_CERGY_ADMIN1;

COMMIT;
EXIT;
